### ISSUE TITLE
Porcupine1, custom wake word

### ISSUE THREAD

**Issue by Krull56** [rhasspy/hassio-addons#29]
Hi Mike,

Thank you so much for your amazing work !!!

French HA user for 3 years, would it be possible to use a french custom wake word generated with the free picovoice platform in your porcupine1 addon like  it is possible with openwakeword?

Have a good day

**Comment by synesthesiam** [comment]
Thanks!

Correct me if I'm wrong, but I believe you can only create custom wake words with porcupine v2 these days. I didn't include a v2 option because it requires API keys, and we found that re-building the add-on too many times would require creating a new account with Picovoice.

I'm also in the process of creating a snowboy add-on that will allow for custom wake words to be created locally, so if you can wait just a bit longer that might be a good option :slightly_smiling_face:

**Comment by Krull56** [comment]
Thank you for your reply.

You're right, picovoice's custom wake words require an api key. I used it on android devices with rhasspy mobile and a french custom wake word. 

I'm taking note of your future add-on with snowboy (seasalt-ai for generate ?) and I'll follow the news about it.

There is no urgency because everything works wonderfully despite my pitiful English accent (convert rpi with seeed respeaker 4 Hat  from rhasspy to home assistant satellite and also use assit microphone with small conf mic)
I prefer to use the English wakeword because the French are ridiculous !!!
It's a little more complicated for my wife 😉

Once again, a big thank  for your work, and your investment since Rhasspy.

**Comment by synesthesiam** [comment]
The snowboy add-on is now available: https://github.com/rhasspy/hassio-addons/tree/master/snowboy

Here is how to train custom wake words: https://github.com/rhasspy/hassio-addons/blob/master/snowboy/DOCS.md#custom-wake-words

**Comment by Krull56** [comment]
So fast !!! You are amazing Mike !
Tanks ( for my wife)  😁

I try this tomorrow .

Good evening

**Comment by Krull56** [comment]
Hello

Just tested with 2 French accent wakewords, and it's working fine.
You are the best 👍👏
Thanks
